on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main
  
permissions:
    contents: read
    pages: write
    id-token: write
  
concurrency:
    group: "pages"
    cancel-in-progress: false
  
jobs:
    lint:
      name: "S206 Seminar Lint"
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [ubuntu-latest]
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12.7'
  
        - name: Install Poetry and Project Dependencies
          run: sh .github/scripts/poetry-script.sh
  
        - name: Install pre-commit and run hooks
          run: sh .github/scripts/pre-commit-script.sh

    test:
      needs: [lint]
      name: "S206 Seminar Test"
      runs-on: ${{ matrix.os }}
  
      strategy:
        matrix:
          os: [ubuntu-latest]
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12.7'
  
        - name: Install Poetry and Project Dependencies
          run: sh .github/scripts/poetry-script.sh
  
        - name: Run the Tests
          run: poetry run task test --cov-report=xml
  
        - name: Upload Cov to CodeCov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
        
        - name: Upload html coverage artifacts
          uses: actions/upload-artifact@v4
          with:
            name: test-html-coverage
            path: htmlcov/

        - name: Upload html report artifacts
          uses: actions/upload-artifact@v4
          with:
            name: test-html-report
            path: ./report.html

    build:
      needs: [test]
      runs-on: ubuntu-latest
      name: S206 Seminar Build Package
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
  
        - name: Install Poetry
          run: sh .github/scripts/poetry-script.sh
  
        - name: Install dependencies
          run: poetry install
  
        - name: Build source and wheel distribution
          run: poetry build
  
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: dist/